{{- range $comp := tuple "ui" "admin" }}
{{- $v := index $.Values $comp }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stratos.fullname" $ }}-{{ $comp }}
  labels:
    {{- include "stratos.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $comp }}
spec:
  type: {{ $v.service.type }}
  selector:
    {{- include "stratos.selector" (dict "ctx" $ "component" $comp) | nindent 4 }}
  ports:
    - name: http
      port: {{ $v.service.port }}
      targetPort: http
{{- end }}
